/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CollegeProject.Gui;

import CollegeProject.Dao.QuestionDao;
import CollegeProject.pojo.Exam;
import CollegeProject.pojo.Question;
import CollegeProject.pojo.QuestionStore;
import CollegeProject.pojo.UserProfile;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.HashMap;
import java.sql.SQLException;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author shiva
 */
public class EditQuestionFrame extends javax.swing.JFrame {
Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
   private Exam editExam;
   private QuestionStore qstore;
   private Question que;
    int prevIndex=-1;
   private HashMap<String,String>options;
   
   private String question,option1,option2,option3,option4,correctOption;
   
   
    public EditQuestionFrame() {
        initComponents();
        this.setSize(screen.width,screen.height);
        lblName.setText("Hello "+UserProfile.getUsername());
        qstore=new QuestionStore();
        options=new HashMap();
        options.put("Option 1", "Answer1");
        options.put("Option 2", "Answer2");
        options.put("Option 3", "Answer3");
        options.put("Option 4", "Answer4");
       
       
        
        }
    public EditQuestionFrame(Exam editExam){
        this();
        this.editExam=editExam;
        jlblTitle.setText("EDITING "+editExam.getLanguage().toUpperCase()+"Paper");
        loadQuestions();
        initializeComboBox();
        
    }
    
   private void initializeComboBox() {
        for(int a=1;a<=editExam.getTotalQuestions();a++)
       cbQueNo.addItem("Que "+a);
    }

private void showQuestions(){
    int index= cbQueNo.getSelectedIndex();
    Question q=qstore.getQuestion(index);
    jtxtQuestion.setText(q.getQuestion());
    jtxtOption1.setText(q.getAnswer1());
     jtxtOption2.setText(q.getAnswer2());
      jtxtOption3.setText(q.getAnswer3());
       jtxtOption4.setText(q.getAnswer4());
       String correctAns=q.getCorrectAnswer();
       String correctOption=getKeyFromValue(correctAns);
       jcCorrectOption.setSelectedItem(correctOption);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtQuestion = new javax.swing.JTextArea();
        jlblOption1 = new javax.swing.JLabel();
        jlblOption2 = new javax.swing.JLabel();
        jlblOption3 = new javax.swing.JLabel();
        jlblOption4 = new javax.swing.JLabel();
        jtxtOption2 = new javax.swing.JTextField();
        jtxtOption1 = new javax.swing.JTextField();
        jtxtOption4 = new javax.swing.JTextField();
        jtxtOption3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcCorrectOption = new javax.swing.JComboBox<>();
        jbtnCancel = new javax.swing.JButton();
        jbtnDone = new javax.swing.JButton();
        jlblQuestionRemaining = new javax.swing.JLabel();
        cbQueNo = new javax.swing.JComboBox<>();
        btnSaveChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jlblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblTitle.setForeground(new java.awt.Color(255, 153, 0));

        lblLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 102, 0));
        lblLogout.setText("Logout");

        jtxtQuestion.setColumns(20);
        jtxtQuestion.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jtxtQuestion.setRows(5);
        jScrollPane1.setViewportView(jtxtQuestion);

        jlblOption1.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption1.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption1.setText("Option 1");

        jlblOption2.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption2.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption2.setText("Option 2");

        jlblOption3.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption3.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption3.setText("Option 3");

        jlblOption4.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption4.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption4.setText("Option 4");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correct Answer");

        jcCorrectOption.setBackground(new java.awt.Color(0, 0, 0));
        jcCorrectOption.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcCorrectOption.setForeground(new java.awt.Color(255, 255, 255));
        jcCorrectOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Option 1", "Option 2", "Option 3", "Option 4" }));

        jbtnCancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnDone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnDone.setText("Done");
        jbtnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoneActionPerformed(evt);
            }
        });

        jlblQuestionRemaining.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblQuestionRemaining.setForeground(new java.awt.Color(255, 255, 255));

        cbQueNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQueNoActionPerformed(evt);
            }
        });

        btnSaveChanges.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblQuestionRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(cbQueNo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlblOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(jlblOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jtxtOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jlblOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlblOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jtxtOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(121, 121, 121)
                                            .addComponent(jtxtOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(172, 253, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnCancel)
                                .addGap(39, 39, 39)
                                .addComponent(btnSaveChanges)
                                .addGap(48, 48, 48)
                                .addComponent(jbtnDone)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcCorrectOption, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLogout)
                                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(68, 68, 68)
                                .addComponent(cbQueNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jlblQuestionRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOption2))
                        .addGap(18, 18, 18)
                        .addComponent(jtxtOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jtxtOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblOption3)
                    .addComponent(jlblOption4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtOption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcCorrectOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnCancel)
                        .addComponent(jbtnDone)))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String getKeyFromValue(String value){
    Set<String>keys=options.keySet();
    for(String k: keys){
        String v=options.get(k);
        System.out.println(v+"=="+value);
        if(v.equals(value))
            return k;
        
    }
    return null;
}

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        
           EditPaperFrame editPaper=new EditPaperFrame();
        editPaper.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoneActionPerformed
        if(!validateInput()){
             JOptionPane.showMessageDialog(null,"Please Fill Input Properly","Error!!",JOptionPane.ERROR_MESSAGE);
            return;
            }
         int index=cbQueNo.getSelectedIndex();
          String optionName=options.get(jcCorrectOption.getSelectedItem());
            que=new Question();
          que.setExamId(editExam.getExamId());
          que.setQno(index+1);
          que.setLanguage(editExam.getLanguage());
          que.setCorrectAnswer(optionName);
          que.setAnswer1(jtxtOption1.getText());
          que.setAnswer2(jtxtOption2.getText());
          que.setAnswer3(jtxtOption3.getText());
          que.setAnswer4(jtxtOption4.getText());
          que.setQuestion(jtxtQuestion.getText());
        qstore.removeQuestion(index);
        qstore.setQuestionAt(index, que);
        try{
           
       QuestionDao.updateQuestions(qstore);
         JOptionPane.showMessageDialog(null,"Your Questions have Been SucessFully update to DB");
            System.out.println(qstore.toString());
         AdminOptionsFrame adminFrame=new AdminOptionsFrame();
         adminFrame.setVisible(true);
         this.dispose();   
         
     }
     catch(SQLException ex){
         JOptionPane.showMessageDialog(null,"DB ERROR","DB error!!",JOptionPane.ERROR_MESSAGE); 
             ex.printStackTrace();
     }
    }//GEN-LAST:event_jbtnDoneActionPerformed

    private void cbQueNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQueNoActionPerformed

        showQuestions();
    }//GEN-LAST:event_cbQueNoActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        if(!validateInput()){
            JOptionPane.showMessageDialog(null,"Please Fill Input Properly","Error!!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int index=cbQueNo.getSelectedIndex();
        String optionName=options.get(jcCorrectOption.getSelectedItem());
        que=new Question();
        que.setExamId(editExam.getExamId());
        que.setQno(index+1);
        que.setLanguage(editExam.getLanguage());
        que.setCorrectAnswer(optionName);
        que.setAnswer1(jtxtOption1.getText());
        que.setAnswer2(jtxtOption2.getText());
        que.setAnswer3(jtxtOption3.getText());
        que.setAnswer4(jtxtOption4.getText());
        que.setQuestion(jtxtQuestion.getText());
        qstore.removeQuestion(index);
        qstore.setQuestionAt(index, que);
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditQuestionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox<String> cbQueNo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnDone;
    private javax.swing.JComboBox<String> jcCorrectOption;
    private javax.swing.JLabel jlblOption1;
    private javax.swing.JLabel jlblOption2;
    private javax.swing.JLabel jlblOption3;
    private javax.swing.JLabel jlblOption4;
    private javax.swing.JLabel jlblQuestionRemaining;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextField jtxtOption1;
    private javax.swing.JTextField jtxtOption2;
    private javax.swing.JTextField jtxtOption3;
    private javax.swing.JTextField jtxtOption4;
    private javax.swing.JTextArea jtxtQuestion;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
    private boolean validateInput(){
        question = jtxtQuestion.getText();
        option1=jtxtOption1.getText().trim();
        option2=jtxtOption2.getText().trim();
        option3=jtxtOption3.getText().trim();
        option4=jtxtOption4.getText().trim();
        correctOption=jcCorrectOption.getSelectedItem().toString();
        if(question.isEmpty()||option1.isEmpty()||option2.isEmpty()||option3.isEmpty()||option4.isEmpty()||correctOption.isEmpty()){
            return false;
        }
        return true;
    }
    private void loadQuestions() {
        try{
            qstore=new QuestionStore();
            ArrayList<Question>questionList=QuestionDao.getQuestionsByExamId(editExam.getExamId());
            for(Question q:questionList){
                qstore.addQuestion(q);
            }
            System.out.println(qstore);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "DB error","Edit question error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

}
