/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CollegeProject.Gui;

import CollegeProject.Dao.ExamDao;
import CollegeProject.Dao.QuestionDao;
import CollegeProject.pojo.Exam;
import CollegeProject.pojo.Question;
import CollegeProject.pojo.QuestionStore;
import CollegeProject.pojo.UserProfile;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author shiva
 */
public class SetQuestionsFram extends javax.swing.JFrame {
Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
   private Exam newExam;
   private QuestionStore qstore;
   private HashMap<String,String>options;
   private int qno;
   private String question,option1,option2,option3,option4,correctOption;
   
   
   
    public SetQuestionsFram() {
        initComponents();
        
        this.setSize(screen.width,screen.height);
        
        lblName.setText("Hello"+UserProfile.getUsername());
        qstore = new QuestionStore();
        options=new HashMap<>();
        options.put("Option 1","Answer1");
         options.put("Option 2","Answer2");
          options.put("Option 3","Answer3");
           options.put("Option 4","Answer4");
           
           qno=1;
           jlblQno.setText(jlblQno.getText()+qno);
        
        
        }
    public SetQuestionsFram(Exam exam){
        this();
        newExam=exam;
        jlblTitle.setText(newExam.getTotalQuestions()+" QUESTIONS REMAINING");
        
       }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltittle = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jlblQno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtQuestion = new javax.swing.JTextArea();
        jlblOption1 = new javax.swing.JLabel();
        jlblOption2 = new javax.swing.JLabel();
        jlblOption3 = new javax.swing.JLabel();
        jlblOption4 = new javax.swing.JLabel();
        jtxtQuestion2 = new javax.swing.JTextField();
        jtxtQuestion1 = new javax.swing.JTextField();
        jtxtQuestion4 = new javax.swing.JTextField();
        jtxtQuestion3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcCorrectOption = new javax.swing.JComboBox<>();
        jbtnNext = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jbtnDone = new javax.swing.JButton();
        jlblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbltittle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbltittle.setForeground(new java.awt.Color(255, 153, 0));
        lbltittle.setText("PAPER SETTING PANEL");

        lblLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 102, 0));
        lblLogout.setText("Logout");

        jlblQno.setBackground(new java.awt.Color(0, 0, 0));
        jlblQno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblQno.setForeground(new java.awt.Color(255, 255, 255));
        jlblQno.setText("Qusetion no : ");

        jtxtQuestion.setColumns(20);
        jtxtQuestion.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jtxtQuestion.setRows(5);
        jScrollPane1.setViewportView(jtxtQuestion);

        jlblOption1.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption1.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption1.setText("Option 1");

        jlblOption2.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption2.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption2.setText("Option 2");

        jlblOption3.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption3.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption3.setText("Option 3");

        jlblOption4.setBackground(new java.awt.Color(0, 0, 0));
        jlblOption4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblOption4.setForeground(new java.awt.Color(255, 255, 255));
        jlblOption4.setText("Option 4");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correct Answer");

        jcCorrectOption.setBackground(new java.awt.Color(0, 0, 0));
        jcCorrectOption.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcCorrectOption.setForeground(new java.awt.Color(255, 255, 255));
        jcCorrectOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Option 1", "Option 2", "Option 3", "Option 4" }));

        jbtnNext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnNext.setText("Next");
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });

        jbtnCancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnDone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnDone.setText("Done");
        jbtnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoneActionPerformed(evt);
            }
        });

        jlblTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTitle.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcCorrectOption, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(69, 69, 69)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlblOption2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .addComponent(jlblOption4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtQuestion2)
                                        .addComponent(jtxtQuestion4)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jbtnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(74, 74, 74)
                                    .addComponent(jbtnNext)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                    .addComponent(jbtnCancel)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lbltittle, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jlblQno, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogout)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltittle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOption2)))
                    .addComponent(jlblQno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblOption4)
                    .addComponent(jlblOption3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jcCorrectOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDone)
                    .addComponent(jbtnNext)
                    .addComponent(jbtnCancel))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
       SetPaperFrame setPaper=new SetPaperFrame();
          setPaper.setVisible(true);
          this.dispose();
          
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        if(validateInput()==false){
            JOptionPane.showMessageDialog(null,"Please fill all the field");
            return;
            
        }
        String optionName=options.get(correctOption);
        Question obj= new Question(newExam.getExamId(),newExam.getLanguage(),qno,question,option1,option2,option3,option4,optionName);
        qstore.addQuestion(obj);
        clearAll();
        jlblTitle.setText(newExam.getTotalQuestions()-qno+"Questions Remaining");
        qno++;
        if(qno>newExam.getTotalQuestions()){
            disableAll();
            JOptionPane.showMessageDialog(null,"Your questions have all been preapred Successfully \n Press the done button to addthem to the database","Exam added",JOptionPane.INFORMATION_MESSAGE);
           System.out.println(qstore);
        }
        else{
            jlblQno.setText(jlblQno.getText()+qno);
        }
        
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jbtnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoneActionPerformed
        if(qno<=newExam.getTotalQuestions()){
           int x= newExam.getTotalQuestions()-qno+1;
           JOptionPane.showMessageDialog(null,"You still have"+x+"Questions remaining ","fill all the questions ",JOptionPane.ERROR_MESSAGE);
           return;
       }
       try{
           boolean done= ExamDao.addExam(newExam);
           if(!done){
               JOptionPane.showMessageDialog(null,"Exam not added in Db","try again",JOptionPane.ERROR_MESSAGE);
               return;
               
           
       }
           QuestionDao.addQuestions(qstore);
           JOptionPane.showMessageDialog(null," Yours questions successfully added to the database","Exam added",JOptionPane.INFORMATION_MESSAGE);
           AdminOptionsFrame adminframe=new AdminOptionsFrame();
           adminframe.setVisible(true);
           this.dispose();
           
       }
       catch(SQLException ex){
           JOptionPane.showMessageDialog(null,"DB Error","Set Questions Error!",JOptionPane.ERROR_MESSAGE);
           
       }
    }//GEN-LAST:event_jbtnDoneActionPerformed
     
    private void clearAll(){
        jtxtQuestion.setText("");
        jtxtQuestion1.setText("");
        jtxtQuestion2.setText("");
        jtxtQuestion3.setText("");
        jtxtQuestion4.setText("");
        jcCorrectOption.setSelectedIndex(0);
        jtxtQuestion.requestFocus();
        
    }
    private void disableAll(){
        jtxtQuestion.setEnabled(false);
        jtxtQuestion1.setEnabled(false);
        jtxtQuestion2.setEnabled(false);
        jtxtQuestion3.setEnabled(false);
        jtxtQuestion4.setEnabled(false);
        jcCorrectOption.setEnabled(false);
        jbtnNext.setEnabled(false);
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetQuestionsFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetQuestionsFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetQuestionsFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetQuestionsFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetQuestionsFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnDone;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JComboBox<String> jcCorrectOption;
    private javax.swing.JLabel jlblOption1;
    private javax.swing.JLabel jlblOption2;
    private javax.swing.JLabel jlblOption3;
    private javax.swing.JLabel jlblOption4;
    private javax.swing.JLabel jlblQno;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextArea jtxtQuestion;
    private javax.swing.JTextField jtxtQuestion1;
    private javax.swing.JTextField jtxtQuestion2;
    private javax.swing.JTextField jtxtQuestion3;
    private javax.swing.JTextField jtxtQuestion4;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbltittle;
    // End of variables declaration//GEN-END:variables

private boolean validateInput(){
    question=jtxtQuestion.getText().trim();
    option1=jtxtQuestion1.getText().trim();
     option2=jtxtQuestion2.getText().trim();
      option3=jtxtQuestion3.getText().trim();
       option4=jtxtQuestion4.getText().trim();
       correctOption=jcCorrectOption.getSelectedItem().toString();
       if(question.isEmpty()||option1.isEmpty()||option2.isEmpty()||option3.isEmpty()||option4.isEmpty()||correctOption.isEmpty()){
           return false;
       }
      return true;
    
}













}
